insert into recipes (title, image_url, description, instructions, cook_time_minutes, calories, protein, fat, carbs)
values ('Oatmeal with Berries', null, 'A nutritious breakfast with oatmeal and fresh berries.',
        '1. Pour hot water over the oats.\n2. Add berries and honey to taste.\n3. Mix and serve.', 10, 320, 10.5, 6.0,
        54.0),
       ('Grilled Chicken Fillet', null, 'Dietary grilled chicken fillet.',
        '1. Marinate the chicken fillet with spices.\n2. Grill for 5-7 minutes on each side.\n3. Serve with vegetables.',
        20, 220, 32.0, 4.0, 5.0),
       ('Caesar Salad', null, 'Classic salad with chicken, croutons, and parmesan cheese.',
        '1. Fry the chicken fillet and slice it.\n2. Mix lettuce, chicken, croutons, and parmesan.\n3. Add dressing.',
        15, 340, 22.0, 18.0, 19.0),
       ('Vegetable Omelette', null, 'Tender omelette with bell pepper, tomatoes, and herbs.',
        '1. Whisk eggs with milk.\n2. Sauté vegetables, then add the eggs.\n3. Cook until done.', 12, 250, 14.0, 17.0,
        9.0),
       ('Cottage Cheese Casserole', null, 'Light and healthy cottage cheese casserole for breakfast or snack.',
        '1. Mix cottage cheese, eggs, sugar, and semolina.\n2. Place in a baking dish and bake at 180°C for 35 minutes.\n3. Cool and slice.',
        40, 180, 13.0, 5.0, 22.0),
       ('Tuna Pasta', null, 'Hearty pasta with canned tuna and tomato sauce.',
        '1. Boil the pasta.\n2. Mix with tuna and tomato sauce.\n3. Garnish with herbs.', 20, 410, 24.0, 8.0, 65.0),
       ('Buckwheat with Mushrooms', null, 'Buckwheat porridge with fried mushrooms and onions.',
        '1. Boil the buckwheat.\n2. Fry mushrooms and onions.\n3. Mix with the buckwheat.', 25, 180, 6.0, 3.0, 34.0),
       ('Steamed Salmon', null, 'Salmon fillet cooked by steaming.',
        '1. Salt and pepper the salmon.\n2. Steam for 10-12 minutes.\n3. Serve with lemon.', 15, 260, 27.0, 15.0, 1.0),
       ('Spinach and Banana Smoothie', null, 'Healthy smoothie with banana, spinach, and yogurt.',
        '1. Blend banana, spinach, and yogurt.\n2. Blend until smooth.', 5, 180, 6.0, 2.0, 36.0),
       ('Steamed Chicken Cutlets', null, 'Dietary chicken cutlets steamed to perfection.',
        '1. Mix ground chicken with onion and spices.\n2. Shape into cutlets.\n3. Steam for 20 minutes.', 25, 195, 18.0,
        7.0, 9.0);