insert into users (username, email, password, role)
values ('johndoe', 'john.doe@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe', 'ROLE_USER'),
       ('janesmith', 'jane.smith@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_USER'),
       ('adminuser', 'admin@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe', 'ROLE_ADMIN'),
       ('alicebrown', 'alice.brown@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_USER'),
       ('bobjones', 'bob.jones@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_USER'),
       ('emmawilson', 'emma.wilson@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_USER'),
       ('michaellee', 'michael.lee@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_USER'),
       ('sarahclark', 'sarah.clark@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_USER'),
       ('davidmartin', 'david.martin@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_USER'),
       ('superadmin', 'super.admin@example.com', '$2a$10$97eUe9WUl8Kb7qpaz3bUROjBsFUiI3b8gGiCSBzDxE4lxUqOfh0fe',
        'ROLE_ADMIN');